tp5

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -30,7 +30,15 @@ jobs:
       - run:
           name: Generate and Publish Checkstyle Badge
           command: |
-            ERRORS=$(grep -o "<error " target/checkstyle-result.xml | wc -l)
+            # Find the checkstyle-result.xml file
+            XML_FILE=$(find . -name "checkstyle-result.xml" | head -n 1)
+            
+            if [ -z "$XML_FILE" ]; then
+              echo "Checkstyle results XML not found!"
+              exit 1
+            fi
+            
+            ERRORS=$(grep -o "<error " "$XML_FILE" | wc -l)
             if [ "$ERRORS" -eq 0 ]; then
               COLOR="brightgreen"
             elif [ "$ERRORS" -le 10 ]; then
@@ -38,11 +46,8 @@ jobs:
             else
               COLOR="red"
             fi
+            
             curl -o checkstyle-badge.svg "https://img.shields.io/badge/Checkstyle-$ERRORS%20errors-$COLOR"
-            cp checkstyle-badge.svg .
-            git add checkstyle-badge.svg
-            git commit -m "Update Checkstyle Badge"
-            git push -f git@github.com:rouabhiamohamed/ceri-m1-techniques-de-test.git gh-pages
 
       - run:
           name: Generate Javadoc
